name: Deploy Frontend (Next.js) to Azure Web App

on:
  push:
    branches: [ master ]
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Optional: Basic sanity check
      - name: Show frontend contents
        run: ls -la frontend

      - name: Deploy to Azure Web App (frontend only)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cts-vibeappea51202-5'
          slot-name: 'Production'
          package: ./frontend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CE95FC4B0F294667AA2287D20F705D4C }}
